apiVersion: v1
kind: Template
labels:
  template: springboot
metadata:
  annotations:
    description: |
      Template to deploy Spring Boot applications
      Documentation available at https://serenity-gitlab.alm.gsnetcloud.corp/serenity-cloud/spring-boot-slim
      Contact support Serenity-Cloud Support
    iconClass: icon-openjdk
    tags: runtime,instant-app,springboot,openjdk
  name: springboot
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app_name: ${APP_NAME}
      template: springboot
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      nodePort: 0
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app_name: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app_name: ${APP_NAME}
      template: springboot
    name: ${APP_NAME}
  spec:
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APP_NAME}
  status: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app_name: ${APP_NAME}
      template: springboot
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app_name: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app_name: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
          template: springboot
      spec:
        containers:
        - env:
          - name: APP_NAME
            value: ${APP_NAME}
          - name: ARTIFACT_URL
            value: ${ARTIFACT_URL}
          - name: JAVA_OPTS_EXT
            value: ${JAVA_OPTS_EXT}
          - name: JAVA_PARAMETERS
            value: ${JAVA_PARAMETERS}
          - name: PROJECT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TZ
            value: ${TZ}
          image: registry.lvtc.gsnet.corp/xis10298/java-serenity:1.0
          imagePullPolicy: IfNotPresent
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: ${POD_MAX_MEM}M
            request:
              memory: ${POD_MAX_MEM}M
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/metadata
            name: podinfo
            readOnly: false
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - metadata:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              name: labels
            - fieldRef:
                fieldPath: metadata.annotations
              name: annotations
          name: podinfo
  status: {}
parameters:
- description: Application name
  displayName: Application Name
  name: APP_NAME
  required: true
- description: Artifact url (jar, zip, tar.gz)
  displayName: Artifact url
  name: ARTIFACT_URL
- description: Executable jar path
  displayName: Jar Path
  name: JAR_PATH
- description: Java options
  displayName: JVM options
  name: JAVA_OPTS_EXT
  value: -Djava.security.egd=file:/dev/./urandom -Xmx160m -XX:NativeMemoryTracking=summary
- description: Application java parameters
  displayName: JVM application parameters
  name: JAVA_PARAMETERS
- description: Maximum memory for the pods (in Megabytes)
  displayName: Pods Max Memory
  name: POD_MAX_MEM
  value: "320"
- description: TimeZone for the running containers.
  displayName: TimeZone
  name: TZ
  value: Europe/Madrid
